# Generated by Django 5.2.4 on 2025-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthquestionnaire',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthquestionnaire',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
