# Generated by Django 4.2.14 on 2025-08-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_suggestion_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthquestionnaire',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='healthquestionnaire',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When admin reviewed', null=True),
        ),
        migrations.AddField(
            model_name='healthquestionnaire',
            name='reviewed_by',
            field=models.CharField(blank=True, help_text='Admin username who reviewed', max_length=150),
        ),
        migrations.AddField(
            model_name='healthquestionnaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text="Doctor's review and suggestions"),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information')], default='pending', max_length=20),
        ),
    ]
