# Generated by Django 4.2.14 on 2025-08-21 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_suggestion_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthquestionnaire',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name_plural': 'Personal Info'},
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='family_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familyhistory'),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='lifestyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lifestyle'),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='measurements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.measurements'),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='medical_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalhistory'),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalinfo'),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='preventive_care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preventivecare'),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='symptoms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symptoms'),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preventivecare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
